# Generated by Django 4.1 on 2022-09-19 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=3, unique=True)),
                ("city", models.CharField(max_length=64, unique=True)),
                ("picture", models.ImageField(upload_to="flight/images/")),
            ],
            managers=[
                ("airports", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airplane", models.CharField(max_length=75)),
                ("duration", models.PositiveIntegerField()),
                ("departing_time", models.DateTimeField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrivals",
                        to="flight.airport",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="flight.airport",
                    ),
                ),
            ],
            options={
                "ordering": ["-departing_time"],
            },
            managers=[
                ("flights", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnic", models.PositiveIntegerField(blank=True)),
                (
                    "flights",
                    models.ManyToManyField(
                        blank=True, related_name="passengers", to="flight.flight"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("passengers", django.db.models.manager.Manager()),
            ],
        ),
    ]
