# Generated by Django 4.1 on 2022-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="cnic",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
