# Generated by Django 4.1 on 2022-09-16 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="departing_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="passenger",
            name="cnic",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
