# Generated by Django 4.1 on 2022-09-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_alter_passenger_cnic"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="cash",
            field=models.PositiveIntegerField(default=10000),
        ),
    ]
