# Generated by Django 4.1 on 2022-09-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_passenger_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="price",
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
    ]
