# Generated by Django 4.1 on 2022-09-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_flight_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="picture",
        ),
        migrations.AddField(
            model_name="airport",
            name="picture",
            field=models.ImageField(default="../l/x.png", upload_to="flight/images/"),
            preserve_default=False,
        ),
    ]
