# Generated by Django 4.1 on 2022-09-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0004_flight_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="cnic",
        ),
    ]
