# Generated by Django 4.1 on 2022-09-17 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0004_remove_flight_picture_airport_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["-departing_time"]},
        ),
        migrations.AddField(
            model_name="flight",
            name="capacity",
            field=models.PositiveIntegerField(
                default=300,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=300,
                        message="Capacity of a Flight must be greater than or equal 300",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
