# Generated by Django 4.1 on 2022-09-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0005_alter_flight_options_flight_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="airplane",
            field=models.CharField(default="F7", max_length=75),
            preserve_default=False,
        ),
    ]
