# Generated by Django 4.1 on 2022-09-19 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flight", "0005_remove_passenger_cnic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="as_passenger",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
